name: update.

on:
  push:
  schedule:
    - cron: "0 15,16,17 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.4' # The Go version to download (if necessary) and use.
      - run: go mod download
      - run: go run generate_readme.go
      - name: Commit files
        run: |
          git add README.md
          git config --local user.email "chunibyo.wly@gmail.com"
          git config --local user.name "Chunibyo"
          git commit -m "Update today's hot topic on $(date)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
